version: '3'

services:
  db:
    container_name: gpt-db
    image: mysql:5.7
    ports:
      - 3309:3306
    volumes:
      - ../../mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gpt
    networks:
      - gptnet


  server:
    container_name: gpt-server
    image: nest:v0.1
    ports:
      - '9998:3002'
    volumes:
      - ./server.env:/app/dist/.env
    depends_on:
      - db
    networks:
      - gptnet


  web:
    container_name: gpt-web
    image: web:v0.1 # 总是使用latest,更新时重新pull该tag镜像即可
    ports:
      - 9997:80
    networks:
      - gptnet
    volumes:
      - ./web.env:/app/dist/.env
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server

networks:
  gptnet:
